# Generated by Django 3.2.8 on 2021-12-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standingorderaccounts',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='standingorderaccounts',
            name='member',
        ),
        migrations.AlterField(
            model_name='standingorderaccounts',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
