# Generated by Django 3.2.8 on 2022-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='cash_withdrawal_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='cash_withdrawal_certification',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='commodity_loan_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='commodity_loan_certification',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='commodity_loan_products',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='components',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='data_imports',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='invoice_management',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='loan_application_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='loan_application_certification',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='loan_criteria_settings',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='loan_request_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='membership_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='membership_exclusiveness_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='service_charges',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='share_purchase_approval',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='system_admin',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='user_manager',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='executives_tasks_model',
            name='utilities',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='0', max_length=3),
        ),
    ]
