# Generated by Django 4.0.5 on 2022-06-22 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFooter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('line1', models.CharField(max_length=100)),
                ('line2', models.CharField(max_length=100)),
                ('line3', models.CharField(max_length=100)),
                ('line4', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
