# Generated by Django 3.2.8 on 2022-03-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_auto_20220304_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_categories',
            name='price_status',
            field=models.CharField(choices=[('0', 'FIXED'), ('1', 'UNFIXED')], default='1', max_length=15),
        ),
    ]
