# Generated by Django 3.2.8 on 2021-12-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_auto_20211208_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standingorderaccounts',
            name='transaction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
