# Generated by Django 4.0.5 on 2022-06-24 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_cooperativebankaccounts_sort_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSignatories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT')], default='SAVINGS', max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.cooperativebankaccounts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
