# Generated by Django 3.2.8 on 2022-03-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_auto_20220304_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity_product_list',
            name='period',
        ),
        migrations.AddField(
            model_name='company_products',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period'),
        ),
        migrations.CreateModel(
            name='Commodity_Period_Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.CharField(max_length=255)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company_products',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period_batch'),
        ),
    ]
