# Generated by Django 3.2.8 on 2021-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_alter_standingorderaccounts_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberswelfareaccounts',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='memberswelfareaccounts',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
