# Generated by Django 3.2.8 on 2021-12-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0005_auto_20211213_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersshareaccounts',
            name='account_number',
        ),
        migrations.AlterField(
            model_name='membersshareaccounts',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
        migrations.DeleteModel(
            name='MembersWelfareAccountsMain',
        ),
    ]
