# Generated by Django 3.2.8 on 2021-12-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_auto_20211213_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberssharepurchaserequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
