# Generated by Django 3.2.8 on 2022-03-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0006_auto_20220306_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_products',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='company_products',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='company_products',
            name='period',
        ),
        migrations.CreateModel(
            name='Company_Products_Prices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period_batch')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.company_products')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.membershipstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
