# Generated by Django 3.2.8 on 2022-03-06 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0007_auto_20220306_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_products',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='company_products',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period_batch'),
        ),
        migrations.AddField(
            model_name='company_products',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period'),
        ),
    ]
