# Generated by Django 4.0.5 on 2022-06-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0007_remove_executives_bank_executives_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansuploaded',
            name='interest_deduction',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SOURCE', 'SOURCE'), ('SPREAD', 'SPREAD')], default='SOURCE', max_length=255),
        ),
    ]
