# Generated by Django 3.2.8 on 2021-12-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_sharessalesrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharessalesrecord',
            old_name='applicant',
            new_name='member',
        ),
    ]
