# Generated by Django 3.2.8 on 2022-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_auto_20220306_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_product_list',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
