# Generated by Django 4.0.5 on 2022-06-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0008_alter_loansuploaded_interest_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='admin_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='interest_deduction',
            field=models.CharField(choices=[('NONE', 'NONE'), ('SOURCE', 'SOURCE'), ('SPREAD', 'SPREAD')], default='SOURCE', max_length=20),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
    ]
