# Generated by Django 3.2.8 on 2021-12-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_rename_applicant_sharessalesrecord_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharessalesrecord',
            old_name='bank_ccount',
            new_name='bank_account',
        ),
    ]
