# Generated by Django 4.0.5 on 2022-06-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0009_loansrepaymentbase_admin_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='nok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersnextofkins'),
        ),
    ]
