# Generated by Django 3.2.8 on 2021-12-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0010_rename_bank_ccount_sharessalesrecord_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscashdeposits',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
