# Generated by Django 4.0.5 on 2022-06-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_remove_loansrepaymentbase_nok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='nok_Relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='nok_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='nok_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='nok_phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
