# Generated by Django 3.2.8 on 2022-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0011_auto_20220306_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_categories',
            name='admin_charges_required',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='commodity_categories',
            name='guarantor_required',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='commodity_categories',
            name='interest_rate_required',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='1', max_length=15),
        ),
    ]
