# Generated by Django 3.2.8 on 2022-03-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_auto_20220306_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_commodity_loam_products_selection',
            name='admin_charge',
        ),
        migrations.RemoveField(
            model_name='members_commodity_loam_products_selection',
            name='duration',
        ),
    ]
