# Generated by Django 3.2.8 on 2021-12-15 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_auto_20211214_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscashdeposits',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberscashdeposits',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes'),
        ),
        migrations.AlterField(
            model_name='memberscashdeposits',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
        ),
    ]
