# Generated by Django 4.0.5 on 2022-06-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0012_loansrepaymentbase_nok_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.loanguarantors'),
        ),
    ]
