# Generated by Django 3.2.8 on 2022-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20220306_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_products_selection',
            name='admin_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
