# Generated by Django 3.2.8 on 2021-12-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0013_auto_20211215_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscashwithdrawals',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawals',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawals',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
