# Generated by Django 3.2.8 on 2022-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0014_members_commodity_loam_products_selection_admin_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_categories',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
