# Generated by Django 4.0.5 on 2022-07-01 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0014_rename_guarantor_loanguarantors_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity_Category_Sub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
