# Generated by Django 4.0.5 on 2022-07-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_commodity_category_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity_category_sub',
            old_name='transaction',
            new_name='category',
        ),
    ]
