# Generated by Django 3.2.8 on 2022-03-06 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_alter_commodity_categories_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_products_selection',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='commodity_categories',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
