# Generated by Django 3.2.8 on 2021-12-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0015_memberscashwithdrawalsapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.certificationstatus'),
        ),
    ]
