# Generated by Django 3.2.8 on 2022-03-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0016_auto_20220306_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members_Commodity_Loam_Application',
            new_name='Members_Commodity_Loan_Application',
        ),
        migrations.RenameModel(
            old_name='Members_Commodity_Loam_Application_Settings',
            new_name='Members_Commodity_Loan_Application_Settings',
        ),
        migrations.RenameModel(
            old_name='Members_Commodity_Loam_Products_Selection',
            new_name='Members_Commodity_Loan_Products_Selection',
        ),
    ]
