# Generated by Django 3.2.8 on 2021-12-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0017_auto_20211215_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscashwithdrawalsmain',
            name='disbursement_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.disbursementofficers'),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsmain',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.memberscashwithdrawalsapplication'),
        ),
    ]
