# Generated by Django 4.0.5 on 2022-07-01 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0017_commodity_category_sub_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treanding_Commodity_Signatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
