# Generated by Django 3.2.8 on 2022-03-06 16:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0017_auto_20220306_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_Commodity_Loan_Application_Temp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('coop_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('admin_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('repayment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('tdate', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members_commodity_loan_products_selection')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
