# Generated by Django 4.0.5 on 2022-07-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0018_treanding_commodity_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='treanding_commodity_signatory',
            name='phone_no',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
