# Generated by Django 3.2.8 on 2021-12-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0018_auto_20211215_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionajustmentrequest',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transactionajustmentrequest',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='transactionajustmentrequest',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
