# Generated by Django 3.2.8 on 2021-12-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0019_auto_20211215_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLoanAjustmentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approval_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalofficers')),
                ('approval_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalstatus')),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.loansrepaymentbase')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
