# Generated by Django 3.2.8 on 2022-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0019_auto_20220306_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_commodity_loan_application',
            name='approval_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application',
            name='certification_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
