# Generated by Django 3.2.8 on 2021-12-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0020_transactionloanajustmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
