# Generated by Django 3.2.8 on 2021-12-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0021_productcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
