# Generated by Django 3.2.8 on 2022-03-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0021_auto_20220306_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='submission_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.submissionstatus'),
        ),
    ]
