# Generated by Django 4.0.5 on 2022-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0022_staff_default_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeductions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='accountssignatories',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='autoreceipt',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cashbook_main',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cashbook_shop',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='commodity_categories',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='commodity_category_sub',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='commodity_product_list',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='company_products',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='company_products_duration',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='compulsorysavings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit_distributions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperativebankaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperativebankaccountsoperationaldesignations',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperativeshopledger',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerid',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_day_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_month_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_year_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_item_write_off_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_cash_flow_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_cash_flow_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_day_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_left_over_fund',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_month_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_selection',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_year_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='daily_sales_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='day_end_desk_office_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='day_end_sales_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='executivepositions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='executives',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditures_day_end_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditures_dialy_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditures_month_end_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='expenditures_year_end_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='failedloanpenalty',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='failedloanpenaltyrecords',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='formautoprints',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='general_cash_sales_selected',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='general_cash_sales_selectedtemp',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='generalticket',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceheader',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='item_write_off_day_end_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='item_write_off_month_end_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='item_write_off_year_end_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemwriteoff',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemwriteofftemp',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='lga',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationguarnators',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplicationsettings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanbasedsavings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanformissuance',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanguarantors',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loannumber',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanrequestattachments',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanrequestsettings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanscleared',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loansrepaymentbase',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loansuploaded',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanunschedulingrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='member_salary_adjustment',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_cash_sales_selected',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application_form_sales',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application_guarantors',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application_settings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_products_selection',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_daily_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_day_end',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_day_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_month_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_year_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_analysis',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_debt_recovery_after_temp',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_selected',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_summary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='members_shop_credit_loans',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersaccountsdomain',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersbankaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberscashdeposits',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawals',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsapplication',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsmain',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersexclusiveness',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipformsalesrecord',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershiprequestadditionalattachment',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershiprequestadditionalinfo',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershiptermination',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipterminationfunddisbursement',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipterminationrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipterminationrequestexception',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membershipterminationtransactionbalances',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersidmanager',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersnextofkins',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersshareaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersshareaccountsmain',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersshareconfigurations',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='membersshareinitialupdaterequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberssharepurchaserequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberswelfare',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberswelfareaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='month_end_sales_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlydeductiongenerationheading',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlydeductionlist',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlydeductionlistgenerated',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlygeneratedtransactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlygroupgeneratedtransactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductiongenerated',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductiongeneratedtransactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductionlist',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyoverdeductionsrefund',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyshopdeductionlist',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyshopdeductionlistgenerated',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyshopgroupgeneratedtransactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='nextofkinsmaximun',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='nonmemberaccountdeductions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='norminalroll',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalledger',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='product_code',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_header',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases_day_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases_month_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases_temp',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchases_year_end_transaction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt_cancelled',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='receipts_shop',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalbookingheaders',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalbookingselections',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalbookingselectionspayment',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalbookingselectionssummary',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalmaincategories',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalpricesettings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='rentalproducts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportfooter',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportheader',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='savingsuploaded',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharesdeductionsavings',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharessalesrecord',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharesunits',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='standingorderaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='standingorderaccountssuspensionreleaserequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='standingorderaccountssuspensionrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='standingorderdeactivatedaccounts',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_auction',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_history',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers_branches',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers_majors',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers_reps',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_users_tasks',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='system_users_tasks_model',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskmanager',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='termination_loan_allowed',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionajustmenthistory',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionajustmentrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionloanajustmentrequest',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionperiods',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactiontypes',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='treanding_commodity_signatory',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawabletransactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='xmas_savings_generated',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='xmas_savings_shortlist',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='xmassavingstransactionperiod',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='xmastransferdefaultsaving',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='year_end_sales_transactions',
            name='processed_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
    ]
