# Generated by Django 3.2.8 on 2022-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0022_members_commodity_loan_application_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
