# Generated by Django 3.2.8 on 2021-12-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0022_stock_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
