# Generated by Django 3.2.8 on 2021-12-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0023_alter_stock_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativeshopledger',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain'),
        ),
    ]
