# Generated by Django 3.2.8 on 2022-03-08 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0023_auto_20220308_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Salary_Adjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('existing_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('current_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approval_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalstatus')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
