# Generated by Django 3.2.8 on 2022-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0024_member_salary_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_salary_adjustment',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
