# Generated by Django 4.0.5 on 2022-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0025_alter_accountdeductions_transaction_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='penalty_status',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('DEFAULTED', 'DEFAULTED')], default='NORMAL', max_length=20),
        ),
    ]
