# Generated by Django 3.2.8 on 2022-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0025_member_salary_adjustment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_salary_adjustment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
