# Generated by Django 4.0.5 on 2022-07-06 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0026_loansrepaymentbase_penalty_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoanPenaltyDuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
