# Generated by Django 3.2.8 on 2022-03-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0026_member_salary_adjustment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity_categories',
            name='admin_charges_minimum',
        ),
        migrations.RemoveField(
            model_name='commodity_categories',
            name='default_admin_charges',
        ),
    ]
