# Generated by Django 3.2.8 on 2022-03-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0027_auto_20220308_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_Commodity_Loan_Application_Guarantors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members_commodity_loan_application')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commodity_categories',
            name='interest_deduction',
        ),
        migrations.DeleteModel(
            name='Members_Commodity_Loan_Application_Temp',
        ),
    ]
