# Generated by Django 4.0.5 on 2022-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0027_failedloanpenaltyduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansuploaded',
            name='loan_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
