# Generated by Django 4.0.5 on 2022-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0028_loansuploaded_loan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansuploaded',
            name='loan_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
