# Generated by Django 4.0.5 on 2022-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0029_alter_loansuploaded_loan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_product_list',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
