# Generated by Django 3.2.8 on 2022-01-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0030_daily_sales_cash_flow_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLevels',
        ),
    ]
