# Generated by Django 4.0.5 on 2022-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0031_commodity_product_list_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantors',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('LOCKED', 'LOCKED')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='coop_no',
            field=models.CharField(blank=True, default='00001', max_length=15, null=True),
        ),
    ]
