# Generated by Django 3.2.8 on 2022-01-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0031_delete_userlevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lock_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.lockedstatus'),
        ),
    ]
