# Generated by Django 3.2.8 on 2022-01-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0032_stock_lock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='lock_status',
        ),
    ]
