# Generated by Django 4.0.5 on 2022-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0032_loanguarantors_status_members_coop_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='coop_no',
            field=models.CharField(default='00001', max_length=15),
        ),
    ]
