# Generated by Django 3.2.8 on 2022-01-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0033_remove_stock_lock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lock_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.lockedstatus'),
        ),
    ]
