# Generated by Django 4.0.5 on 2022-07-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0034_alter_members_coop_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ippis_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
