# Generated by Django 3.2.8 on 2022-01-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0035_suppliers_suppliers_majors_suppliers_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='phone',
        ),
        migrations.CreateModel(
            name='Suppliers_Branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='suppliers_reps',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.suppliers_branches'),
            preserve_default=False,
        ),
    ]
