# Generated by Django 3.2.8 on 2022-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0036_auto_20220112_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers_branches',
            name='address',
            field=models.TextField(),
        ),
    ]
