# Generated by Django 4.0.5 on 2022-07-12 01:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0036_commodity_loan_upload_transaction_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity_product_list',
            name='category',
        ),
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_details',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_details',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_details',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_details',
            name='repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='commodity_loan_upload_transaction_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.company_products'),
        ),
    ]
