# Generated by Django 3.2.8 on 2022-01-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0037_alter_suppliers_branches_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers_reps',
            name='supplier',
        ),
    ]
