# Generated by Django 4.0.5 on 2022-07-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0039_commodity_loan_upload_transaction_details_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_header',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_category_sub'),
        ),
    ]
