# Generated by Django 3.2.8 on 2022-01-13 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0039_purchases_purchases_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='purchases_temp',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='purchases_temp',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchases_temp',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='purchases_temp',
            name='processed_by',
        ),
        migrations.CreateModel(
            name='Purchase_Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.suppliers_branches')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.suppliers_reps')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.purchase_header'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases_temp',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.purchase_header'),
            preserve_default=False,
        ),
    ]
