# Generated by Django 3.2.8 on 2022-01-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0041_alter_purchase_header_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_header',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus'),
        ),
    ]
