# Generated by Django 4.0.5 on 2022-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0041_alter_commodity_loan_upload_transaction_header_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_header',
            name='loan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
