# Generated by Django 4.0.5 on 2022-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0043_commodity_loan_upload_transaction_details_company_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_details',
            name='total_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
