# Generated by Django 3.2.8 on 2022-01-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0044_alter_purchase_header_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase_header',
            table='purchase_header',
        ),
    ]
