# Generated by Django 4.0.5 on 2022-07-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0044_commodity_loan_upload_transaction_details_total_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standingorderaccounts',
            name='status',
        ),
    ]
