# Generated by Django 3.2.8 on 2022-01-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0045_alter_purchase_header_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='adminmaster',
            table='adminmaster',
        ),
        migrations.AlterModelTable(
            name='approvalstatus',
            table='approvalstatus',
        ),
        migrations.AlterModelTable(
            name='certificationstatus',
            table='certificationstatus',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
        migrations.AlterModelTable(
            name='datejoineduploadstatus',
            table='datejoineduploadstatus',
        ),
        migrations.AlterModelTable(
            name='exclusivestatus',
            table='exclusivestatus',
        ),
        migrations.AlterModelTable(
            name='loancategory',
            table='loancategory',
        ),
        migrations.AlterModelTable(
            name='loanschedulestatus',
            table='loanschedulestatus',
        ),
        migrations.AlterModelTable(
            name='lockedstatus',
            table='lockedstatus',
        ),
        migrations.AlterModelTable(
            name='membershipstatus',
            table='membershipstatus',
        ),
        migrations.AlterModelTable(
            name='processingstatus',
            table='processingstatus',
        ),
        migrations.AlterModelTable(
            name='savingsuploadstatus',
            table='savingsuploadstatus',
        ),
        migrations.AlterModelTable(
            name='sharesuploadstatus',
            table='sharesuploadstatus',
        ),
        migrations.AlterModelTable(
            name='submissionstatus',
            table='submissionstatus',
        ),
        migrations.AlterModelTable(
            name='transactionstatus',
            table='transactionstatus',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='usertype',
        ),
        migrations.AlterModelTable(
            name='welfareuploadstatus',
            table='welfareuploadstatus',
        ),
        migrations.AlterModelTable(
            name='withdrawalstatus',
            table='withdrawalstatus',
        ),
    ]
