# Generated by Django 4.0.5 on 2022-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0046_standingorderaccounts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
