# Generated by Django 4.0.5 on 2022-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0047_alter_members_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_upload_transaction_header',
            name='ledger_status',
            field=models.CharField(choices=[('UNPROCESSED', 'UNPROCESSED'), ('PROCESSED', 'PROCESSED')], default='UNPROCESSED', max_length=20),
        ),
    ]
