# Generated by Django 3.2.8 on 2022-01-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0047_auto_20220113_2134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase_header',
            table='purchaseheader',
        ),
        migrations.AlterModelTable(
            name='purchases',
            table='purchases',
        ),
        migrations.AlterModelTable(
            name='purchases_temp',
            table='purchasetemp',
        ),
    ]
