# Generated by Django 3.2.8 on 2022-01-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0048_auto_20220114_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers_reps',
            name='branch',
        ),
        migrations.AddField(
            model_name='suppliers_reps',
            name='suppliers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.suppliers'),
            preserve_default=False,
        ),
    ]
