# Generated by Django 4.0.5 on 2022-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0049_personalledgersavingsposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalledgersavingsposting',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='CREDIT', max_length=20),
        ),
    ]
