# Generated by Django 3.2.8 on 2022-01-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0050_purchase_header_certification_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
