# Generated by Django 4.0.5 on 2022-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0051_personalledgermanualposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalledgermanualposting',
            name='account_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalledgermanualposting',
            name='sources',
            field=models.CharField(default='SAVINGS', max_length=30),
        ),
        migrations.AlterField(
            model_name='personalledgermanualposting',
            name='transaction',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PersonalLedgerSavingsPosting',
        ),
    ]
