# Generated by Django 4.0.5 on 2022-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0052_personalledgermanualposting_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyjointdeductiongenerated',
            name='verification',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
