# Generated by Django 4.0.5 on 2022-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0053_monthlyjointdeductiongenerated_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeductionlistgenerated',
            name='verification',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
