# Generated by Django 4.0.5 on 2022-07-15 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0054_monthlydeductionlistgenerated_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxillaryDeductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('transaction_period', models.DateField(blank=True, null=True)),
                ('ippis_no', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('transaction_status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED')], default='UNTREATED', max_length=20)),
                ('salary_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.salaryinstitution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
