# Generated by Django 3.2.8 on 2022-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0054_auto_20220116_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminmaster',
            table='admin_master',
        ),
        migrations.AlterModelTable(
            name='itemwriteoffreasons',
            table='item_write_off_reasons',
        ),
        migrations.AlterModelTable(
            name='loancategory',
            table='Loan_Category',
        ),
        migrations.AlterModelTable(
            name='membershipstatus',
            table='membership_status',
        ),
    ]
