# Generated by Django 3.2.8 on 2022-01-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0056_auto_20220116_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
