# Generated by Django 4.0.5 on 2022-07-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0056_auxillarydeductions_coop_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeductionlistgenerated',
            name='aux_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
