# Generated by Django 3.2.8 on 2022-01-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0057_stock_unit_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.stock'),
        ),
    ]
