# Generated by Django 4.0.5 on 2022-07-16 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0057_monthlydeductionlistgenerated_aux_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoanPenaltyEnabler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
