# Generated by Django 3.2.8 on 2022-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0058_daily_sales_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=1, max_length=255)),
                ('address1', models.CharField(default=1, max_length=255)),
                ('address2', models.CharField(default=1, max_length=255)),
                ('phone_no', models.CharField(default=1, max_length=255)),
            ],
            options={
                'db_table': 'Invoice_Header',
                'abstract': False,
            },
        ),
    ]
