# Generated by Django 4.0.5 on 2022-07-18 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0058_failedloanpenaltyenabler'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanLessRepaymentEnable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
