# Generated by Django 3.2.8 on 2022-01-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0059_invoiceheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceheader',
            old_name='name',
            new_name='title',
        ),
    ]
