# Generated by Django 3.2.8 on 2022-01-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0060_rename_name_invoiceheader_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWriteOffTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalstatus')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.stock')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.itemwriteoffreasons')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus')),
            ],
            options={
                'db_table': 'Item_Write_Off_Temp',
                'abstract': False,
            },
        ),
    ]
