# Generated by Django 4.0.5 on 2022-07-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0060_cooperativebankaccountsdesignationheaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativebankaccountsoperationaldesignations',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.cooperativebankaccountsdesignationheaders'),
        ),
    ]
