# Generated by Django 4.0.5 on 2022-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0062_alter_cooperativebankaccountsoperationaldesignations_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
