# Generated by Django 4.0.5 on 2022-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0063_membershiprequest_date_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='period',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
    ]
