# Generated by Django 3.2.8 on 2022-01-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0063_auto_20220122_0859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchases',
            table=None,
        ),
    ]
