# Generated by Django 4.0.5 on 2022-07-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0064_remove_loanrequest_batch_remove_loanrequest_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypes',
            name='loan_path',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PROJECT', 'PROJECT'), ('EMERGENCY', 'EMERGENCY')], default='NONE', max_length=20),
        ),
    ]
