# Generated by Django 3.2.8 on 2022-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0065_formautoprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formautoprint',
            name='status',
            field=models.BooleanField(choices=[('YES', 'YES'), ('NO', 'NO')]),
        ),
    ]
