# Generated by Django 4.0.5 on 2022-07-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0066_loanrequest_short_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='short_list_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
