# Generated by Django 3.2.8 on 2022-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0066_alter_formautoprint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formautoprint',
            name='status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
    ]
