# Generated by Django 4.0.5 on 2022-07-19 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0067_loanrequest_short_list_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequestShortListing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('approval_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=30)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('short_listed_date', models.DateField(blank=True, null=True)),
                ('short_list_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED')], default='UNTREATED', max_length=20)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.loanrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
