# Generated by Django 4.0.5 on 2022-07-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0068_loanrequestshortlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='approval_comment',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approval_officer',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approved_amount',
        ),
    ]
