# Generated by Django 3.2.8 on 2022-01-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0068_yesno'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAutoPrints',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.yesno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
