# Generated by Django 4.0.5 on 2022-07-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0069_remove_loanrequest_approval_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='short_list_by',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='short_listed',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='short_listed_date',
        ),
    ]
