# Generated by Django 3.2.8 on 2022-01-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0069_formautoprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sales',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='daily_sales',
            name='item_name',
        ),
    ]
