# Generated by Django 3.2.8 on 2022-01-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0070_auto_20220125_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sales',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales_cash_flow_summary',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_sales_summary',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='general_cash_sales_selected',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='general_cash_sales_selectedtemp',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
