# Generated by Django 4.0.5 on 2022-07-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0071_remove_loanrequestshortlisting_short_list_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanformissuance',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.loanrequestshortlisting'),
        ),
    ]
