# Generated by Django 3.2.8 on 2022-01-26 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0072_auto_20220126_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_credit_purchase_analysis',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members_credit_purchase_summary',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members_credit_sales_selected',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
