# Generated by Django 3.2.8 on 2022-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0073_auto_20220126_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
