# Generated by Django 3.2.8 on 2022-01-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0074_generalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sales_summary',
            name='sales_category',
        ),
        migrations.AddField(
            model_name='daily_sales',
            name='sales_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.salescategory'),
        ),
    ]
