# Generated by Django 3.2.8 on 2022-01-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0077_cooperative_shop_cash_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
        ),
    ]
