# Generated by Django 4.0.5 on 2022-07-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0077_loanrequest_loan_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanformissuance',
            name='applicant',
        ),
        migrations.AddField(
            model_name='loanformissuance',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanformissuance',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
            preserve_default=False,
        ),
    ]
