# Generated by Django 4.0.5 on 2022-07-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0078_remove_loanformissuance_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanformissuance',
            name='admin_charge',
        ),
    ]
