# Generated by Django 3.2.8 on 2022-01-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0078_alter_cooperative_shop_cash_deposit_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative_shop_cash_deposit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.banks'),
        ),
        migrations.AddField(
            model_name='cooperative_shop_cash_deposit',
            name='coop_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.cooperativebankaccounts'),
        ),
        migrations.AddField(
            model_name='cooperative_shop_cash_deposit',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
