# Generated by Django 3.2.8 on 2022-01-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0079_auto_20220128_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative_shop_cash_deposit',
            name='processing_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.processingstatus'),
        ),
    ]
