# Generated by Django 4.0.5 on 2022-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0079_remove_loanformissuance_admin_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformissuance',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
