# Generated by Django 4.0.5 on 2022-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0080_loanformissuance_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformissuance',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
