# Generated by Django 3.2.8 on 2022-01-28 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0081_daily_cash_deposit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativeshopledger',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
