# Generated by Django 4.0.5 on 2022-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0081_loanformissuance_amount_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformissuance',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanformissuance',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
