# Generated by Django 4.0.5 on 2022-07-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0083_loanrequest_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformissuance',
            name='loan_path',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PROJECT', 'PROJECT'), ('EMERGENCY', 'EMERGENCY')], default='PROJECT', max_length=20),
        ),
    ]
