# Generated by Django 3.2.8 on 2022-01-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0083_auto_20220128_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_header',
            name='tdate',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='tdate',
        ),
        migrations.RemoveField(
            model_name='purchases_temp',
            name='tdate',
        ),
    ]
