# Generated by Django 4.0.5 on 2022-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0084_loanformissuance_loan_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeductions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='auxillarydeductions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity_loan_upload_transaction_details',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity_loan_upload_transaction_header',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit',
            name='status2',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit_distributions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperativeshopledger',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_day_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_month_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_cash_deposit_year_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_item_write_off_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_cash_flow_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_cash_flow_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_day_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_left_over_fund',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_month_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_selection',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_sales_item_return_year_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='daily_sales_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='day_end_desk_office_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='day_end_sales_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenditures_day_end_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenditures_dialy_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenditures_month_end_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='expenditures_year_end_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=15),
        ),
        migrations.AlterField(
            model_name='failedloanpenaltyrecords',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='general_cash_sales_selected',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='general_cash_sales_selectedtemp',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item_write_off_day_end_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item_write_off_month_end_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='item_write_off_year_end_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemwriteoff',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemwriteofftemp',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationguarnators',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationsettings',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationshortlisting',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanformissuance',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequestattachments',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequestsettings',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequestshortlisting',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanscleared',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loansuploaded',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanunschedulingrequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='member_salary_adjustment',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_cash_sales_selected',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application_form_sales',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_application_settings',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_commodity_loan_products_selection',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_daily_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_day_end',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_day_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_month_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_loans_cash_receipt_year_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_analysis',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_selected',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_credit_sales_summary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_shop_credit_loans',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberscashdeposits',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawals',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsapplication',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsmain',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersexclusiveness',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipformsalesrecord',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershiptermination',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipterminationfunddisbursement',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipterminationrequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipterminationrequestexception',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershipterminationtransactionbalances',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersshareaccounts',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersshareinitialupdaterequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberssharepurchaserequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberswelfareaccounts',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='month_end_sales_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlydeductiongenerationheading',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlydeductionlist',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlydeductionlistgenerated',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlygeneratedtransactions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlygroupgeneratedtransactions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductiongenerated',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductiongeneratedtransactions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyjointdeductionlist',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyshopdeductionlist',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyshopdeductionlistgenerated',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyshopgroupgeneratedtransactions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='nonmemberaccountdeductions',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='norminalroll',
            name='transaction_status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalledgermanualposting',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase_header',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchases_day_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchases_month_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchases_year_end_transaction',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalbookingheaders',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalbookingselections',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalbookingselectionspayment',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='rentalbookingselectionssummary',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='savingsuploaded',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharessalesrecord',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='standingorderaccountssuspensionreleaserequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='standingorderaccountssuspensionrequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='standingorderdeactivatedaccounts',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionajustmentrequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionloanajustmentrequest',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='xmas_savings_shortlist',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='year_end_sales_transactions',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
    ]
