# Generated by Django 4.0.5 on 2022-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0085_alter_accountdeductions_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationshortlisting',
            name='loan_number',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
