# Generated by Django 3.2.8 on 2022-01-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0086_transactiontypes_form_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipformsalesrecord',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
