# Generated by Django 4.0.5 on 2022-07-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0087_alter_loanapplicationshortlisting_loan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='description',
        ),
    ]
