# Generated by Django 3.2.8 on 2022-01-31 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0088_day_end_desk_office_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
