# Generated by Django 4.0.5 on 2022-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0089_loanrequest_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
