# Generated by Django 3.2.8 on 2022-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0089_loansrepaymentbase_tdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDeductionGenerationHeaders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
