# Generated by Django 4.0.5 on 2022-08-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0091_rename_approved_amount_loanrequest_applied_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersexclusiveness',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='membersexclusiveness',
            name='period',
        ),
    ]
