# Generated by Django 3.2.8 on 2022-02-02 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0091_monthlydeductiongenerationheading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyShopDeductionCertified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tdate', models.DateField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
                ('salary_institution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.salaryinstitution')),
                ('transaction_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionperiods')),
                ('transaction_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeductionListGeneratedCertified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tdate', models.DateField()),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
                ('salary_institution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.salaryinstitution')),
                ('transaction_period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionperiods')),
                ('transaction_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
