# Generated by Django 3.2.8 on 2022-02-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0092_monthlydeductionlistgeneratedcertified_monthlyshopdeductioncertified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOverdeductionsRefund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=255)),
                ('ref_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tdate', models.DateField()),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersaccountsdomain')),
                ('over_deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.monthlydeductionlistgeneratedcertified')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
