# Generated by Django 4.0.5 on 2022-08-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0092_remove_membersexclusiveness_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='existing_loan_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
