# Generated by Django 4.0.5 on 2022-08-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0093_loanrequest_existing_loan_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersexclusiveness',
            name='task',
        ),
    ]
