# Generated by Django 3.2.8 on 2022-02-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0093_monthlyoverdeductionsrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyoverdeductionsrefund',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
        ),
    ]
