# Generated by Django 4.0.5 on 2022-08-05 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0094_remove_membersexclusiveness_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersexclusiveness',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.exceptablecriterias'),
            preserve_default=False,
        ),
    ]
