# Generated by Django 3.2.8 on 2022-02-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0094_alter_monthlyoverdeductionsrefund_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyoverdeductionsrefund',
            old_name='over_deduction',
            new_name='amount',
        ),
    ]
