# Generated by Django 3.2.8 on 2022-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0095_rename_over_deduction_monthlyoverdeductionsrefund_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyoverdeductionsrefund',
            old_name='amount',
            new_name='over_deduction',
        ),
    ]
