# Generated by Django 4.0.5 on 2022-08-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0096_remove_auxillarydeductions_coop_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxillarydeductions',
            name='coop_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
