# Generated by Django 3.2.8 on 2022-02-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0097_monthlydeductionlistgeneratedcertified_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.membershipstatus'),
        ),
    ]
