# Generated by Django 4.0.5 on 2022-08-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0098_commodity_loan_invoicing_products_selection_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            old_name='product',
            new_name='description',
        ),
    ]
