# Generated by Django 3.2.8 on 2022-02-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0099_termination_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termination_types',
            options={'ordering': ['id']},
        ),
    ]
