# Generated by Django 4.0.5 on 2022-08-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0099_rename_product_commodity_loan_invoicing_products_selection_temp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='status',
            field=models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20),
        ),
    ]
