# Generated by Django 3.2.8 on 2022-02-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0100_alter_termination_types_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShipTerminationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('applied_date', models.DateField()),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('tdate', models.DateField()),
                ('approval_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalofficers')),
                ('approval_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.approvalstatus')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus')),
                ('termination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.termination_types')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
