# Generated by Django 4.0.5 on 2022-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0100_commodity_loan_invoicing_products_selection_temp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='reciept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
