# Generated by Django 4.0.5 on 2022-08-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0101_commodity_loan_invoicing_products_selection_temp_reciept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
