# Generated by Django 4.0.5 on 2022-08-12 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0102_rename_reciept_commodity_loan_invoicing_products_selection_temp_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
