# Generated by Django 4.0.5 on 2022-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0103_commodity_loan_invoicing_products_selection_temp_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_loan_invoicing_products_selection_temp',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
