# Generated by Django 3.2.8 on 2022-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0104_auto_20220207_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_category',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
