# Generated by Django 4.0.5 on 2022-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0104_commodity_loan_invoicing_products_selection_temp_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
