# Generated by Django 4.0.5 on 2022-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0105_members_commodity_loan_application_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application_form_sales',
            name='receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
