# Generated by Django 3.2.8 on 2022-02-07 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0105_alter_commodity_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity_category',
            options={},
        ),
        migrations.CreateModel(
            name='Non_Monetary_Loan_Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('interest_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('admin_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('admin_charges_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('default_admin_charges', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('guarantors', models.IntegerField(default=0)),
                ('loan_age', models.IntegerField(default=0)),
                ('admin_charges_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.admincharges')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.commodity_category')),
                ('form_print', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.yesno')),
                ('interest_deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.interestdeductionsource')),
                ('multiple_loan_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.multipleloanstatus')),
                ('receipt_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.receipttypes')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.membershipstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
