# Generated by Django 4.0.5 on 2022-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0106_members_commodity_loan_application_form_sales_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='standing_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
