# Generated by Django 4.0.5 on 2022-08-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0107_members_commodity_loan_application_standing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
