# Generated by Django 3.2.8 on 2022-02-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0107_commodity_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_categories',
            name='receipt_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.receipttypes'),
        ),
    ]
