# Generated by Django 4.0.5 on 2022-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0108_members_commodity_loan_application_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='short_listed',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
    ]
