# Generated by Django 4.0.5 on 2022-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0109_members_commodity_loan_application_short_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='serial_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
