# Generated by Django 4.0.5 on 2022-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0110_members_commodity_loan_application_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='loan_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
