# Generated by Django 3.2.8 on 2022-02-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0110_commodity_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='admin_charges_rating',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='category',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='form_print',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='interest_deduction',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='multiple_loan_status',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='receipt_type',
        ),
        migrations.RemoveField(
            model_name='non_monetary_loan_settings',
            name='status',
        ),
        migrations.DeleteModel(
            name='Commodity_Category',
        ),
        migrations.DeleteModel(
            name='Non_Monetary_Loan_Settings',
        ),
    ]
