# Generated by Django 3.2.8 on 2022-02-07 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0111_auto_20220207_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity_Product_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_categories')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.membershipstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
