# Generated by Django 4.0.5 on 2022-08-22 05:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0112_monthlydeductionlistgenerated_rectified'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrepaymentbase',
            name='completed',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
        migrations.CreateModel(
            name='Members_Commodity_Loan_Completed_Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
