# Generated by Django 3.2.8 on 2022-02-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0112_commodity_product_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_product_list',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
