# Generated by Django 4.0.5 on 2022-08-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0115_members_commodity_receipt_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='phone_no1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members_commodity_loan_application',
            name='phone_no2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
