# Generated by Django 3.2.8 on 2022-02-10 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0116_company_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_Commodity_Loam_Products_Selection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('company_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('coop_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('admin_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.company_products')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
