# Generated by Django 3.2.8 on 2022-02-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0117_members_commodity_loam_products_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_products_selection',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
            preserve_default=False,
        ),
    ]
