# Generated by Django 3.2.8 on 2022-02-10 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0118_members_commodity_loam_products_selection_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members_Commodity_Loam_Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('coop_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('admin_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('certification_comment', models.TextField(blank=True, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalofficers')),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalstatus')),
                ('certification_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.certificationofficers')),
                ('certification_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.certificationstatus')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members_commodity_loam_products_selection')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Members_Commodity_Loam_Application_Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members_commodity_loam_application')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
