# Generated by Django 3.2.8 on 2022-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0119_members_commodity_loam_application_members_commodity_loam_application_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_application',
            name='repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
