# Generated by Django 3.2.8 on 2022-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0120_members_commodity_loam_application_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_application',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
