# Generated by Django 4.0.5 on 2022-08-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0120_wrongfuldeductiontransfer_transaction_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeductionlist',
            name='rectified',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
