# Generated by Django 3.2.8 on 2022-02-10 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0121_members_commodity_loam_application_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_application',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members_commodity_loam_application_settings',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members_commodity_loam_products_selection',
            name='tdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
