# Generated by Django 3.2.8 on 2022-02-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0122_auto_20220210_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_commodity_loam_application_settings',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='members_commodity_loam_application_settings',
            name='tdate',
        ),
    ]
