# Generated by Django 4.0.5 on 2022-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0122_members_xmas_commodity_loan_products_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_xmas_commodity_loan_products_selection',
            name='selection_completed',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
