# Generated by Django 4.0.5 on 2022-08-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0124_members_xmas_commodity_loan_products_selection_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_xmas_commodity_loan_products_selection_summary',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period_batch'),
        ),
        migrations.AddField(
            model_name='members_xmas_commodity_loan_products_selection_summary',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.commodity_period'),
        ),
    ]
