# Generated by Django 3.2.8 on 2022-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0125_dedicated_commodity_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicated_commodity_price_list',
            name='batch',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
