# Generated by Django 4.0.5 on 2022-08-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0125_members_xmas_commodity_loan_products_selection_summary_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmas_savings_shortlist',
            name='payment_channel',
            field=models.CharField(choices=[('NONE', 'NONE'), ('CASH', 'CASH'), ('TRANSFERRED', 'TRANSFERRED')], default='CASH', max_length=100),
        ),
    ]
