# Generated by Django 3.2.8 on 2022-02-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0126_dedicated_commodity_price_list_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedicated_commodity_price_list',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='dedicated_commodity_price_list',
            name='tyear',
        ),
        migrations.AddField(
            model_name='dedicated_commodity_price_list',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.dedicated_commodity_period'),
            preserve_default=False,
        ),
    ]
