# Generated by Django 4.0.5 on 2022-08-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0126_alter_xmas_savings_shortlist_payment_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmas_savings_shortlist',
            name='payment_channel',
            field=models.CharField(choices=[('NONE', 'NONE'), ('CASH', 'CASH'), ('TRANSFERRED', 'TRANSFERRED')], default='NONE', max_length=100),
        ),
    ]
