# Generated by Django 4.0.5 on 2022-08-31 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0127_alter_xmas_savings_shortlist_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity_product_list',
            name='no_in_pack',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
