# Generated by Django 3.2.8 on 2022-02-12 00:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0127_auto_20220211_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essential_Commodity_Product_Select',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tdate', models.DateField()),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.dedicated_commodity_price_list')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.membershipstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
