# Generated by Django 3.2.8 on 2022-02-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0128_essential_commodity_product_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_select',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
            preserve_default=False,
        ),
    ]
