# Generated by Django 4.0.5 on 2022-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0128_commodity_product_list_no_in_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_products',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
