# Generated by Django 4.0.5 on 2022-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0129_company_products_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmas_savings_generated',
            name='start_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xmas_savings_generated',
            name='stop_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
