# Generated by Django 3.2.8 on 2022-02-12 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0129_essential_commodity_product_select_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_select',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='essential_commodity_product_select',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus'),
        ),
    ]
