# Generated by Django 4.0.5 on 2022-09-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0130_xmas_savings_generated_start_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmas_savings_generated',
            name='start_point',
        ),
        migrations.RemoveField(
            model_name='xmas_savings_generated',
            name='stop_point',
        ),
    ]
