# Generated by Django 3.2.8 on 2022-02-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0131_essential_commodity_product_selection_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='approval_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalofficers'),
        ),
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='approval_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalstatus'),
        ),
    ]
