# Generated by Django 4.0.5 on 2022-09-11 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0131_remove_xmas_savings_generated_start_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField()),
                ('status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('participant_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('participant', models.CharField(choices=[('MEMBER', 'MEMBER'), ('NON MEMBER', 'NON MEMBER')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.event_title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
