# Generated by Django 3.2.8 on 2022-02-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0132_auto_20220212_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
