# Generated by Django 4.0.5 on 2022-09-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0132_event_title_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_title',
            old_name='start_date',
            new_name='pdate',
        ),
        migrations.RemoveField(
            model_name='event_title',
            name='stop_date',
        ),
    ]
