# Generated by Django 3.2.8 on 2022-02-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0133_essential_commodity_product_selection_summary_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essential_commodity_product_selection_summary',
            name='total',
        ),
    ]
