# Generated by Django 4.0.5 on 2022-09-14 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0133_rename_start_date_event_title_pdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentPeriods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('transaction_period', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
