# Generated by Django 4.0.5 on 2022-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0134_adjustmentperiods'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionajustmentrequest',
            name='adjustment_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
