# Generated by Django 4.0.5 on 2022-09-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0136_remove_transactionajustmentrequest_adjustment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipterminationrequest',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
        ),
    ]
