# Generated by Django 3.2.8 on 2022-02-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0136_alter_essential_commodity_product_selection_summary_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential_commodity_product_selection_summary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.essential_commodity_product_select'),
        ),
    ]
