# Generated by Django 3.2.8 on 2022-02-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0137_alter_essential_commodity_product_selection_summary_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_commodity_loam_application',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members_commodity_loam_application_settings',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='members_commodity_loam_products_selection',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
