# Generated by Django 4.0.5 on 2022-09-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0137_alter_membershipterminationrequest_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='saving_status',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
    ]
