# Generated by Django 4.0.5 on 2022-09-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0138_loanrequest_saving_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='ignore_restriction',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
    ]
