# Generated by Django 3.2.8 on 2022-02-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0138_auto_20220215_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_select',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
