# Generated by Django 4.0.5 on 2022-09-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0139_loanrequest_ignore_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ignore_restriction',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30),
        ),
    ]
