# Generated by Django 3.2.8 on 2022-02-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0139_auto_20220216_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
