# Generated by Django 3.2.8 on 2022-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0140_auto_20220216_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_select',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
