# Generated by Django 3.2.8 on 2022-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0141_essential_commodity_product_select_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential_commodity_product_selection_summary',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
