# Generated by Django 4.0.5 on 2022-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0142_saving_fund_transfer_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformissuance',
            name='print_status',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=20),
        ),
    ]
