# Generated by Django 3.2.8 on 2022-02-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0142_essential_commodity_product_selection_summary_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.CharField(default=1, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
