# Generated by Django 4.0.5 on 2022-09-19 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0143_loanformissuance_print_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyShopdeductionList_Aux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('transaction_period', models.DateField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20)),
                ('processing_status', models.CharField(choices=[('UNPROCESSED', 'UNPROCESSED'), ('PROCESSED', 'PROCESSED')], default='UNPROCESSED', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.members')),
                ('salary_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.salaryinstitution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
