# Generated by Django 3.2.8 on 2022-02-18 22:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0143_proformainvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoicedCommodityLoan_Application_summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('repayment', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('duration', models.CharField(max_length=4)),
                ('certification_comment', models.TextField(blank=True, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=255, null=True)),
                ('tdate', models.DateField()),
                ('approval_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalofficers')),
                ('approval_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.approvalstatus')),
                ('certification_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.certificationofficers')),
                ('certification_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.certificationstatus')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
