# Generated by Django 3.2.8 on 2022-02-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0144_proformainvoicedcommodityloan_application_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProformaInvoicedCommodityLoan_Application_summary',
            new_name='Customized_Commodity_Loan_Application_Summary',
        ),
    ]
