# Generated by Django 4.0.5 on 2022-09-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0145_monthly_deduction_normalization_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_deduction_normalization_list',
            old_name='cagtegory',
            new_name='category',
        ),
    ]
