# Generated by Django 3.2.8 on 2022-02-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0145_rename_proformainvoicedcommodityloan_application_summary_customized_commodity_loan_application_summa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customized_commodity_loan_application_summary',
            old_name='ticket',
            new_name='invoice',
        ),
    ]
