# Generated by Django 3.2.8 on 2022-02-19 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0146_rename_ticket_customized_commodity_loan_application_summary_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_commodity_loan_application_summary',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
            preserve_default=False,
        ),
    ]
