# Generated by Django 4.0.5 on 2022-09-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0147_personalledgermanualposting_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_comment',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_officer',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawalsapplication',
            name='certification_status',
        ),
    ]
