# Generated by Django 3.2.8 on 2022-02-19 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0147_customized_commodity_loan_application_summary_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_commodity_loan_application_summary',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
