# Generated by Django 3.2.8 on 2022-02-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0148_customized_commodity_loan_application_summary_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customized_commodity_loan_application_summary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.companies'),
        ),
    ]
