# Generated by Django 4.0.5 on 2022-09-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0148_remove_memberscashwithdrawalsapplication_certification_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscashwithdrawalsmain',
            name='disbursement_date',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawalsmain',
            name='disbursement_officer',
        ),
        migrations.RemoveField(
            model_name='memberscashwithdrawalsmain',
            name='disbursement_status',
        ),
        migrations.AddField(
            model_name='banks',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='memberscashwithdrawalsmain',
            name='channel',
            field=models.CharField(choices=[('TRANSFER', 'TRANSFER'), ('CHEQUE', 'CHEQUE')], default='TRANSFER', max_length=30),
        ),
        migrations.DeleteModel(
            name='MembersCashWithdrawals',
        ),
    ]
