# Generated by Django 4.0.5 on 2022-09-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0149_remove_memberscashwithdrawalsmain_disbursement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscashwithdrawalsmain',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
