# Generated by Django 3.2.8 on 2022-02-19 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0149_customized_commodity_loan_application_summary_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customized_Commodity_Loan_Application_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('tdate', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.customized_commodity_loan_application_summary')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
