# Generated by Django 4.0.5 on 2022-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0150_memberscashwithdrawalsmain_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscashwithdrawalsmain',
            name='sources',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('SHARES', 'SHARES'), ('WELFARE', 'WELFARE')], default='SAVINGS', max_length=20),
        ),
    ]
