# Generated by Django 3.2.8 on 2022-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0150_customized_commodity_loan_application_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customized_commodity_loan_application_details',
            name='transaction',
        ),
        migrations.AddField(
            model_name='customized_commodity_loan_application_details',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
