# Generated by Django 4.0.5 on 2022-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0151_memberscashwithdrawalsmain_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscashwithdrawalsmain',
            name='particulars',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
