# Generated by Django 3.2.8 on 2022-02-19 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0151_auto_20220219_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customized_Commodity_Loan_Application_Payslip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('tdate', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.customized_commodity_loan_application_summary')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cooperative.transactionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
