# Generated by Django 4.0.5 on 2022-09-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0152_memberscashwithdrawalsmain_particulars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscashwithdrawalsmain',
            name='sources',
        ),
        migrations.AddField(
            model_name='memberscashwithdrawalsmain',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes'),
        ),
    ]
