# Generated by Django 4.0.5 on 2022-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0153_remove_memberscashwithdrawalsmain_sources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentperiods',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashbook_main',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashbook_shop',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='commodity_categories',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity_category_sub',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='INACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodity_product_list',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='company_products',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperative_shop_cash_deposit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cooperativebankaccountsoperationaldesignations',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cust_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='executives',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='INACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='loansrepaymentbase',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='members_commodity_receipt_phone_no',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='INACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersaccountsdomain',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersbankaccounts',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersnextofkins',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='membersshareaccountsmain',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalledger',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalpricesettings',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='standingorderaccounts',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionperiods',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactiontypes',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='xmassavingstransactionperiod',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('TERMINATED', 'TERMINATED')], default='ACTIVE', max_length=20),
        ),
    ]
