# Generated by Django 4.0.5 on 2022-09-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0154_alter_adjustmentperiods_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptermination',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='approval_comment',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='approval_officer',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='lock_status',
        ),
        migrations.RemoveField(
            model_name='membershiptermination',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='membersshareaccountsmain',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes'),
        ),
        migrations.DeleteModel(
            name='MemberShipTerminationTransactionBalances',
        ),
    ]
