# Generated by Django 4.0.5 on 2022-09-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0155_remove_membershiptermination_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersshareaccountsmain',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cooperative.transactiontypes'),
            preserve_default=False,
        ),
    ]
