# Generated by Django 4.0.5 on 2022-09-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0156_alter_membersshareaccountsmain_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersshareaccountsmain',
            name='shares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
