# Generated by Django 4.0.5 on 2022-09-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0157_alter_membersshareaccountsmain_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersshareinitialupdaterequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.membersshareaccountsmain'),
        ),
        migrations.DeleteModel(
            name='MembersShareAccounts',
        ),
    ]
