# Generated by Django 4.0.5 on 2022-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0158_alter_membersshareinitialupdaterequest_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersshareaccountsmain',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
