# Generated by Django 4.0.5 on 2022-09-27 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0159_alter_membersshareaccountsmain_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesActiveYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
