# Generated by Django 4.0.5 on 2022-09-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0160_sharesactiveyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersshareaccountsmain',
            name='effective_date',
        ),
    ]
