# Generated by Django 4.0.5 on 2022-09-29 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0161_remove_membersshareaccountsmain_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberssharepurchaserequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.members'),
        ),
        migrations.CreateModel(
            name='LoanApprovedAmountUpgrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('existing_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('approval_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=30)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.loanformissuance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
