# Generated by Django 4.0.5 on 2022-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0162_alter_memberssharepurchaserequest_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapprovedamountupgrade',
            name='date_applied',
        ),
        migrations.AddField(
            model_name='loanapprovedamountupgrade',
            name='new_amount_saved',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapprovedamountupgrade',
            name='prev_amount_saved',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
