# Generated by Django 4.0.5 on 2022-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0163_remove_loanapprovedamountupgrade_date_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapprovedamountupgrade',
            name='approval_date',
        ),
        migrations.AddField(
            model_name='general_cash_sales_selected',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
