# Generated by Django 4.0.5 on 2022-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0164_remove_loanapprovedamountupgrade_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_cash_sales_selected',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='general_cash_sales_selected',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
