# Generated by Django 4.0.5 on 2022-09-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0165_general_cash_sales_selected_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_cash_sales_selected',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='members_cash_sales_selected',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
