# Generated by Django 4.0.5 on 2022-09-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0167_members_credit_sales_selected_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='coop_no',
            field=models.CharField(default='A00001', max_length=15, unique=True),
        ),
    ]
