# Generated by Django 4.0.5 on 2022-10-01 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0168_alter_members_coop_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Auction_Price_Update_Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.CharField(default='ADMIN', max_length=100)),
                ('tdate', models.DateField(default=django.utils.timezone.now)),
                ('prev_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approval_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_status', models.CharField(choices=[('UNPROCESSED', 'UNPROCESSED'), ('PROCESSED', 'PROCESSED')], default='UNPROCESSED', max_length=30)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNTREATED', 'UNTREATED'), ('TREATED', 'TREATED'), ('ARCHIVED', 'ARCHIVED')], default='UNTREATED', max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperative.stock_auction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
