# Generated by Django 4.0.5 on 2022-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0169_stock_auction_price_update_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_auction_price_update_request',
            name='prev_price',
        ),
        migrations.AlterField(
            model_name='stock_auction_price_update_request',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=30),
        ),
    ]
