# Generated by Django 4.0.5 on 2022-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0171_stock_auction_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_auction_request',
            name='new_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock_auction_request',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
