# Generated by Django 4.0.5 on 2022-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0172_stock_auction_request_new_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_auction',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_auction',
            name='expiry_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
