# Generated by Django 4.0.5 on 2022-10-03 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0173_alter_stock_auction_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_shop_credit_loans',
            name='deduction_period',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
