# Generated by Django 4.0.5 on 2022-10-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0174_members_shop_credit_loans_deduction_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_shop_credit_loans',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='members_shop_credit_loans',
            name='balance',
        ),
    ]
