# Generated by Django 4.0.5 on 2022-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0177_monthlyshopdeductionschedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyshopdeductionschedules',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loansrepaymentbase',
            name='schedule_status',
            field=models.CharField(choices=[('UNSCHEDULED', 'UNSCHEDULED'), ('SCHEDULED', 'SCHEDULED'), ('SUSPENDED', 'SUSPENDED')], default='UNSCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='members_shop_credit_loans',
            name='schedule_status',
            field=models.CharField(choices=[('UNSCHEDULED', 'UNSCHEDULED'), ('SCHEDULED', 'SCHEDULED'), ('SUSPENDED', 'SUSPENDED')], default='UNSCHEDULED', max_length=20),
        ),
    ]
